//
// Created by joped on 09/10/2020.
//

#ifndef ADRC_PROJECT_INTERNETCONNECTIVITY_SEARCHCOMMERCIAL_H
#define ADRC_PROJECT_INTERNETCONNECTIVITY_SEARCHCOMMERCIAL_H
#include "graph.h"
#include "Stacks.h"

int* BFS_C(List**,int,int);
int* DFS_C(List**,int,int);





#endif //ADRC_PROJECT_INTERNETCONNECTIVITY_SEARCHCOMMERCIAL_H
